# -*- coding: utf-8 -*-
"""AES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIh5wE8WLJHcRmhtWqbekHDm2psndkvN
"""

!pip install galois

from rich import print
from rich.table import Table
from rich.box import MINIMAL
import galois


# Define AES Field: GF(2^8)


GF256 = galois.GF(2**8, irreducible_poly="x^8 + x^4 + x^3 + x + 1")


# GF(2^8) Operations

def multiplicative_inverse(value):
    """Return the multiplicative inverse in GF(2^8)."""
    if value == 0:
        return 0

    return int(GF256(value) ** 254)


# Affine Transformation

def affine_matrix_multiply(byte):
    """Apply the AES affine transformation matrix."""

    matrix = [
        [1, 0, 0, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 0, 1, 1, 1],
        [1, 1, 1, 0, 0, 0, 1, 1],
        [1, 1, 1, 1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1, 1],
    ]

    result = 0

    for row in range(8):
        bit = 0

        for col in range(8):
            if matrix[row][col]:
                bit ^= (byte >> col) & 1

        result |= bit << row

    return result


def add_affine_constant(byte):
    """Apply the AES affine constant (0x63)."""
    return byte ^ 0x63


def transform_matrix(byte):
    """Complete affine transformation."""
    return add_affine_constant(affine_matrix_multiply(byte))



# S-Box Generation

def generate_sbox():
    """Generate the AES S-Box."""
    return [transform_matrix(multiplicative_inverse(i)) for i in range(256)]


def generate_inverse_sbox(sbox):
    """Generate the inverse AES S-Box."""

    inverse_sbox = [0] * 256

    for i in range(256):
        inverse_sbox[sbox[i]] = i

    return inverse_sbox

# Validation

def verify_sbox(generated_sbox, reference_sbox):
    """Verify that the generated S-Box matches the reference S-Box."""
    return generated_sbox == reference_sbox


def check_nonlinearity(sbox, input_a, input_b):
    """Demonstrate the non-linearity property of the AES S-Box."""

    sbox_a = sbox[input_a]
    sbox_b = sbox[input_b]
    sbox_xor = sbox[input_a ^ input_b]

    left_side = sbox_a ^ sbox_b
    right_side = sbox_xor

    print()

    print(f"A = {input_a:02X} H, S(A) = {sbox_a:02X} H")
    print(f"B = {input_b:02X} H, S(B) = {sbox_b:02X} H")
    print(f"S(A) ⊕ S(B) = {left_side:02X} H")
    print(f"S(A ⊕ B) = {right_side:02X} H")

    print(
        "[bold blue]Non-linearity property satisfied?[/bold blue]",
        "[bold purple]Yes[/bold purple]"
        if left_side != right_side
        else "[bold purple]No[/bold purple]",
    )


def is_sbox_one_to_one(sbox):
    """Check that every S-Box output is unique."""

    seen = [False] * 256

    for value in sbox:
        if seen[value]:
            print(f"[red]Duplicate found: 0x{value:02X}[/red]")
            return False

        seen[value] = True

    return True


# Output Table

from rich.box import SIMPLE_HEAD


def print_lookup_table(table, title):
    """Display a lookup table using Rich formatting."""

    rich_table = Table(
        title=title,
        show_header=True,
        show_lines=False,
        box=SIMPLE_HEAD,
        padding=(0, 1),
        row_styles=[" ", " "],
    )

    rich_table.add_column(" ", justify="center", no_wrap=True)
    rich_table.add_column("│", justify="center", no_wrap=True, style="dim")

    for i in range(16):
        rich_table.add_column(f"{i:X}", justify="center", no_wrap=True)

    for row in range(16):
        row_label = f"{row:X}"
        row_values = [
            f"{table[row * 16 + col]:02X}"
            for col in range(16)
        ]

        rich_table.add_row(row_label, "│", *row_values)

    print(rich_table)

# Official AES S-Box (FIPS-197)

OFFICIAL_SBOX = [
    0x63, 0x7C, 0x77, 0x7B, 0xF2, 0x6B, 0x6F, 0xC5, 0x30, 0x01, 0x67, 0x2B, 0xFE, 0xD7, 0xAB, 0x76,
    0xCA, 0x82, 0xC9, 0x7D, 0xFA, 0x59, 0x47, 0xF0, 0xAD, 0xD4, 0xA2, 0xAF, 0x9C, 0xA4, 0x72, 0xC0,
    0xB7, 0xFD, 0x93, 0x26, 0x36, 0x3F, 0xF7, 0xCC, 0x34, 0xA5, 0xE5, 0xF1, 0x71, 0xD8, 0x31, 0x15,
    0x04, 0xC7, 0x23, 0xC3, 0x18, 0x96, 0x05, 0x9A, 0x07, 0x12, 0x80, 0xE2, 0xEB, 0x27, 0xB2, 0x75,
    0x09, 0x83, 0x2C, 0x1A, 0x1B, 0x6E, 0x5A, 0xA0, 0x52, 0x3B, 0xD6, 0xB3, 0x29, 0xE3, 0x2F, 0x84,
    0x53, 0xD1, 0x00, 0xED, 0x20, 0xFC, 0xB1, 0x5B, 0x6A, 0xCB, 0xBE, 0x39, 0x4A, 0x4C, 0x58, 0xCF,
    0xD0, 0xEF, 0xAA, 0xFB, 0x43, 0x4D, 0x33, 0x85, 0x45, 0xF9, 0x02, 0x7F, 0x50, 0x3C, 0x9F, 0xA8,
    0x51, 0xA3, 0x40, 0x8F, 0x92, 0x9D, 0x38, 0xF5, 0xBC, 0xB6, 0xDA, 0x21, 0x10, 0xFF, 0xF3, 0xD2,
    0xCD, 0x0C, 0x13, 0xEC, 0x5F, 0x97, 0x44, 0x17, 0xC4, 0xA7, 0x7E, 0x3D, 0x64, 0x5D, 0x19, 0x73,
    0x60, 0x81, 0x4F, 0xDC, 0x22, 0x2A, 0x90, 0x88, 0x46, 0xEE, 0xB8, 0x14, 0xDE, 0x5E, 0x0B, 0xDB,
    0xE0, 0x32, 0x3A, 0x0A, 0x49, 0x06, 0x24, 0x5C, 0xC2, 0xD3, 0xAC, 0x62, 0x91, 0x95, 0xE4, 0x79,
    0xE7, 0xC8, 0x37, 0x6D, 0x8D, 0xD5, 0x4E, 0xA9, 0x6C, 0x56, 0xF4, 0xEA, 0x65, 0x7A, 0xAE, 0x08,
    0xBA, 0x78, 0x25, 0x2E, 0x1C, 0xA6, 0xB4, 0xC6, 0xE8, 0xDD, 0x74, 0x1F, 0x4B, 0xBD, 0x8B, 0x8A,
    0x70, 0x3E, 0xB5, 0x66, 0x48, 0x03, 0xF6, 0x0E, 0x61, 0x35, 0x57, 0xB9, 0x86, 0xC1, 0x1D, 0x9E,
    0xE1, 0xF8, 0x98, 0x11, 0x69, 0xD9, 0x8E, 0x94, 0x9B, 0x1E, 0x87, 0xE9, 0xCE, 0x55, 0x28, 0xDF,
    0x8C, 0xA1, 0x89, 0x0D, 0xBF, 0xE6, 0x42, 0x68, 0x41, 0x99, 0x2D, 0x0F, 0xB0, 0x54, 0xBB, 0x16,
]



# Main

def main():
    # Generate multiplicative inverse lookup table
    multiplicative_inverse_table = [
        multiplicative_inverse(i) for i in range(256)
    ]
    print_lookup_table(
        multiplicative_inverse_table,
        "Multiplicative Inverse in GF(2^8)"
    )

    # Display affine transformation before XOR with the constant
    affine_table = [
        affine_matrix_multiply(multiplicative_inverse(i))
        for i in range(256)
    ]
    print_lookup_table(
        affine_table,
        "Affine Transformation (Before Constant XOR)"
    )

    # Generate AES S-Box
    sbox = generate_sbox()
    print_lookup_table(sbox, "Final AES S-Box")

    # Generate inverse S-Box
    inverse_sbox = generate_inverse_sbox(sbox)
    print_lookup_table(inverse_sbox, "AES Inverse S-Box")

    # Validation


    print("[bold black]Comparison Results:[/bold black]")

    print(
        "[bold blue]\nS-Box matches the official AES S-Box?[/bold blue]",
        "[bold purple]Yes[/bold purple]"
        if verify_sbox(sbox, OFFICIAL_SBOX)
        else "[bold purple]No[/bold purple]",
    )

    print(
        "[bold blue]Inverse S-Box matches the official AES inverse S-Box?[/bold blue]",
        "[bold purple]Yes[/bold purple]"
        if verify_sbox(
            inverse_sbox,
            generate_inverse_sbox(OFFICIAL_SBOX),
        )
        else "[bold purple]No[/bold purple]",
    )

    print()


    # S-Box Lookup Test


    try:
        print("[bold black]S-Box Test:[/bold black]")

        input_value = int(input("Enter a hexadecimal value (00-FF): "), 16)

        if not 0 <= input_value <= 0xFF:
            raise ValueError

        sbox_value = sbox[input_value]
        inverse_value = inverse_sbox[sbox_value]

        print(
            f"\nInput = {input_value:02X} H"
            f"\nS({input_value:02X}) = {sbox_value:02X} H"
            f"\nS⁻¹({sbox_value:02X}) = {inverse_value:02X} H"
        )

        print(
            "[bold blue]Input = S⁻¹(S(Input))?[/bold blue]",
            "[bold purple]Yes[/bold purple]"
            if input_value == inverse_value
            else "[bold purple]No[/bold purple]",
        )

    except ValueError:
        print("[red]Invalid hexadecimal input (must be between 00 and FF).[/red]")


    # Non-Linearity Test


    try:
        print("\n[bold black]Non-Linearity Test:[/bold black]")

        input_a = int(input("Enter hexadecimal value A (00-FF): "), 16)
        input_b = int(input("Enter hexadecimal value B (00-FF): "), 16)

        if not (0 <= input_a <= 0xFF and 0 <= input_b <= 0xFF):
            raise ValueError

        check_nonlinearity(sbox, input_a, input_b)

    except ValueError:
        print("[red]Invalid hexadecimal input (must be between 00 and FF).[/red]")


    # One-to-One Property Test


    print("\n[bold black]One-to-One Property Test:[/bold black]")

    print(
        "[bold blue]Is the S-Box one-to-one?[/bold blue]",
        "[bold purple]Yes[/bold purple]"
        if is_sbox_one_to_one(sbox)
        else "[bold purple]No[/bold purple]",
    )


if __name__ == "__main__":
    main()